<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="title" id="title">Relatório de Convênios</p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-right">
                                    <a href="javascript:window.history.go(-1)" class="btn btn-default">Voltar</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="content">
                        <form method="post">
                                    
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>CNPJ</label>
                                        <input type="text" autofocus="true" class="form-control" id="relatorio_cnpj" name="cnpj" placeholder="CNPJ" value="">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Razão Social</label>
                                        <input type="text" class="form-control" id="relatorio_razao_social" name="razao_social" placeholder="Razão Social" value="">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nome Fantasia</label>
                                        <input type="text" class="form-control" id="relatorio_nome_fantasia" name="nome_fantasia" placeholder="Nome Fantasia" value="">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <p>Relatório</p>
                                    <div class="content table-responsive table-full-width">
                                        <table id="relatorio-table" class="table table-striped table-no-bordered table-hover dataTable dtr-inline table-dentistas">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>CNPJ</th>
                                                    <th>Razão Social</th>
                                                    <th>Nome Fantasia</th>
                                                </tr>
                                            </thead>
                                            <tbody id="tbody">
                                            
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <a href="<?php echo URL_BASE; ?>relatorios" class="btn btn-defualt">Página principal de relatórios</a>
                            <a href="#" id="relatorio-pdf" class="btn btn-default pull-right">Gerar relatório PDF</a>
                            <div class="clearfix"></div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>