<!--  
	Arquivo gerado pelo Build_Core 
	@author Maickon Rangel - maickon4developers@gmail.com
	Prodigio Framework - 2017
	View: relatorios
-->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Relatórios</h4>
                        <p>Escolha o tipo de relatório desejado.</p>
                    </div>
                    <div class="content">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-agenda">
                                        <i class="pe-7s-notebook big"></i>
                                    </a>
                                    <br>
                                    <label>Agenda</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-fornecedor">
                                        <i class="pe-7s-network big"></i>
                                    </a>
                                    <br>
                                    <label>Fornecedores</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-convenio">
                                        <i class="pe-7s-note2 big"></i>
                                    </a>
                                    <br>
                                    <label>Convênios</label>        
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-tratamento">
                                        <i class="pe-7s-bandaid big"></i>
                                    </a>
                                    <br>
                                    <label>Tipos de Tratamentos</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-produto-protese">
                                        <i class="pe-7s-box1 big"></i>
                                    </a>
                                    <br>
                                    <label>Produtos de Protese</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>relatorio-produto-medicamento">
                                        <i class="pe-7s-box1 big"></i>
                                    </a>
                                    <br>
                                    <label>Produtos de Medicamentos</label>        
                                </div>
                            </div>
                        </div>

                        <!-- <div class="row">
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php //echo URL_BASE; ?>relatorio-dentista">
                                        <i class="pe-7s-id big"></i>
                                    </a>
                                    <br>
                                    <label>Dentistas</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php //echo URL_BASE; ?>relatorio-paciente">
                                        <i class="pe-7s-users big"></i>
                                    </a>
                                    <br>
                                    <label>Pacientes</label>        
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php //echo URL_BASE; ?>relatorio-secretaria    ">
                                        <i class="pe-7s-user-female big"></i>
                                    </a>
                                    <br>
                                    <label>Secretárias</label>        
                                </div>
                            </div>
                        </div> -->
                        
                        <div class="row">
                            <div class="header">
                                <h3>Visualização, pesquisa e alteração.</h3>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>alterar-senha">
                                        <i class="pe-7s-lock big"></i>
                                    </a>
                                    <br>
                                    <label>Alterar Senha</label>        
                                </div>
                            </div>
                        
                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>painel/usuarios/show/<?php echo $_SESSION['id']; ?>">
                                        <i class="pe-7s-user big"></i>
                                    </a>
                                    <br>
                                    <label>Visualizar seus Dados</label>        
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group main_icon">
                                    <a href="<?php echo URL_BASE; ?>usuarios">
                                        <i class="pe-7s-users big"></i>
                                    </a>
                                    <br>
                                    <label>Listar Usuários</label>        
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>