<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="title">Relatório de Paciente</p>
                            </div>
                            <div class="col-md-6">
                                <p class="text-right">
                                    <a href="javascript:window.history.go(-1)" class="btn btn-default">Voltar</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="content">
                        <form method="post">
                           
                            <div class="row">
                                
                            </div>
                            
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text" class="form-control" id="relatorio_nome" name="nome" placeholder="Nome" value="" />
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <p>Relatório</p>
                                    <div class="content table-responsive table-full-width">
                                        <table class="table table-striped table-no-bordered table-hover dataTable dtr-inline table-dentistas">
                                            <thead>
                                                <tr>
                                                    <th>ID</th>
                                                    <th>Nome</th>
                                                </tr>
                                            </thead>
                                            <tbody id="tbody">
                                            
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <a href="<?php echo URL_BASE; ?>relatorios" class="btn btn-defualt">Página principal de relatórios</a>
                            <button type="submit" class="btn btn-default pull-right">Gerar relatório PDF</button>
                            <div class="clearfix"></div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>