<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <?php $this->alert->show($_QUERY); ?>
                    <div class="header">
                        <p class="title">Novo Produto - Medicamentos</p>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>criar-produto-medicamento" data-toggle="validator">
                           
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text" autofocus="true" class="form-control" id="nome" name="nome" placeholder="Nome" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Cor da Tarja</label>
                                        <input type="text" class="form-control" id="cor_tarja" name="cor_tarja" placeholder="Tarja" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Forma</label>
                                        <input type="text" class="form-control" id="forma" name="forma" placeholder="Forma" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Preço</label>
                                        <input type="text" class="form-control" id="preco" name="preco" placeholder="Preço" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>
                                        <textarea style="height: 200px;" class="form-control" id="descricao" name="descricao" placeholder="Descrição" required=""></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                            <button type="submit" class="btn btn-default pull-right">Salvar dados</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>