<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <?php $this->alert->show($_QUERY); ?>
                    <div class="header">
                        <p class="title">Novo Usuário</p>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>add-usuario" data-toggle="validator">
                            <?php if ($_SESSION['tipo'] == 3): ?>
                                <input type="hidden" name="fk_tipos" value="3">
                            <?php elseif ($_SESSION['tipo'] == 4): ?>
                                <input type="hidden" name="fk_tipos" value="4">
                            <?php endif; ?>
                            <div class="row">
                                <?php if ($_SESSION['tipo'] == 1): ?>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Tipo de usuário</label>
                                        <select autofocus="true" id="tipo_usuario" name="fk_tipos" class="form-control selectpicker" data-title="Tipo de usuário" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                            <option value="">Selecione</option>
                                            <?php foreach ($tipos as $key => $value): ?>
                                            <option <?php echo ($value->id == 3)?'selected':''; ?> value="<?php echo $value->id; ?>"><?php echo $value->nome; ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <?php elseif ($_SESSION['tipo'] == 2): ?>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Tipo de usuário</label>
                                        <select autofocus="true" id="tipo_usuario" name="fk_tipos" class="form-control selectpicker" data-title="Tipo de usuário" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                            <option value="">Selecione</option>
                                            <?php foreach ($tipos as $key => $value): ?>
                                                <?php if ($value->id != 1): ?>
                                                 <option <?php echo ($value->id == 3)?'selected':''; ?> value="<?php echo $value->id; ?>"><?php echo $value->nome; ?></option>
                                                <?php endif ?>
                                            <?php endforeach ?>
                                        </select>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <?php endif ?>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Telefone Celular</label>
                                        <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Telefone" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password" class="form-control" name="senha" placeholder="Senha" id="senha" value="" data-minlength="6" data-error="Mínimo de seis (6) digitos" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Confirmar Senha</label>
                                        <input type="password" class="form-control" placeholder="Confirmar senha" value="" data-match="#senha" data-match-error="Atenção! As senhas não estão iguais." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>

                            <div id="form_cliente_secretaria">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Data de Nascimento</label>
                                            <div class="input-group date datepicker">
                                                <input type="text" class="form-control" id="nascimento" name="nascimento" placeholder="Data de Nascimento" value="" required />
                                                <span class="input-group-addon">
                                                    <span class="glyphicon glyphicon-calendar"></span>
                                                </span>
                                            </div>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Sexo</label>
                                            <select id="sexo" name="sexo" class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                                <option value="">Selecione</option>
                                                <option value="m">Masculino</option>
                                                <option value="f">Feminino</option>
                                            </select>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>RG</label>
                                            <input type="text" class="form-control" id="rg" name="rg" placeholder="RG" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>CPF</label>
                                            <input type="text" class="form-control" id="cpf" name="cpf" placeholder="CPF" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group" id="convenios">
                                            <label>Convênio</label>
                                            <select autofocus="true" id="fk_convenios" name="fk_convenios" class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($convenios as $key => $value): ?>
                                                     <option value="<?php echo $value->id; ?>"><?php echo $value->nome_fantasia; ?></option>
                                                <?php endforeach ?>
                                            </select>
                                            <span class="help-block with-errors"></span>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Telefone Residencial</label>
                                            <input type="text" class="form-control" id="telefone_residencial" name="telefone_residencial" placeholder="Telefone Residencial" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Rua</label>
                                            <input type="text" class="form-control" id="rua" name="rua" placeholder="Rua" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Bairro</label>
                                            <input type="text" class="form-control" id="bairro" name="bairro" placeholder="Bairro" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label>Número</label>
                                            <input type="text" class="form-control" id="numero" name="numero" placeholder="Número" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Cidade</label>
                                            <input type="text" class="form-control" id="cidade" name="cidade" placeholder="Cidade" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Cep</label>
                                            <input type="text" class="form-control" id="cep" name="cep" placeholder="Cep" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Estado</label>
                                            <select id="fk_estados" name="fk_estados" class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($estados as $key => $value): ?>
                                                <option value="<?php echo $value->id; ?>"><?php echo "{$value->nome} ({$value->uf})"; ?></option>
                                                <?php endforeach ?>
                                            </select>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div id="form_dentista">
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>CRO</label>
                                            <input type="text" class="form-control" id="cro" name="cro" placeholder="CRO" value="" required>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Dias de atendimento</label>
                                            <select autofocus="true" id="dias" name="fk_dias[]" multiple class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                                <option value="">Selecione</option>
                                                <?php foreach ($dias as $key => $value): ?>
                                                <option value="<?php echo $value->id; ?>"><?php echo $value->nome; ?></option>
                                                <?php endforeach ?>
                                            </select>
                                            <div class="help-block with-errors" id="horario-erro"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Atende das</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control timepicker" id="horario_atendimento_inicio" name="horario_atendimento_inicio" placeholder="Hora de início" value="" required>
                                                <span class="input-group-addon" style="cursor: pointer;">
                                                    <span class="glyphicon glyphicon-time"></span>
                                                </span>
                                            </div>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label>Até as</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control timepicker" id="horario_atendimento_fim" name="horario_atendimento_fim" placeholder="Hora de fim" value="" required>
                                                <span class="input-group-addon" style="cursor: pointer;">
                                                    <span class="glyphicon glyphicon-time"></span>
                                                </span>
                                            </div>
                                            <div class="help-block with-errors"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                            <button type="submit" class="btn btn-default pull-right">Salvar dados</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>