<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul class="nav navbar-nav navbar-left">
                <li>
                    <a href="<?php echo URL_BASE; ?>">
                        Home
                    </a>
                </li>
                <li>
                    <a href="<?php echo URL_BASE ?>tratamentos">
                        Tratamentos
                    </a>
                </li>
                <li>
                    <a href="<?php echo URL_BASE ?>agendas">
                        Agenda
                    </a>
                </li>
                <li>
                    <a href="<?php echo URL_BASE ?>produtos">
                       Produtos
                    </a>
                </li>
                <li>
                    <a href="<?php echo URL_BASE ?>convenios">
                       Convênios
                    </a>
                </li>
                <li>
                    <a href="<?php echo URL_BASE ?>fornecedores">
                       Fornecedores
                    </a>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            Equipe Sis Odonto Desenvolvimento - &copy <?php echo date("Y"); ?>
        </p>
    </div>
</footer>