<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><?php echo "Bem vindo ".$_SESSION['nome']; ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <!-- <ul class="nav navbar-nav navbar-left">
            </ul> -->

            <ul class="nav navbar-nav navbar-right">
                <!-- <li>
                   <a href="">
                       Account
                    </a>
                </li> -->
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Usuário
                            <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <?php if ($_SESSION['tipo'] == 1 || $_SESSION['tipo'] == 2): ?>
                        <li><a href="<?php echo URL_BASE; ?>usuarios">Listar usuários</a></li>
                        <li><a href="<?php echo URL_BASE; ?>novo-usuario">Novo usuário</a></li>
                        <?php endif ?>
                        <li><a href="<?php echo URL_BASE; ?>painel/usuarios/show/<?php echo $_SESSION['id'];?>">Seus dados</a></li>
                        <?php if ($_SESSION['tipo'] == 1 || $_SESSION['tipo'] == 2): ?>
                        <li><a href="<?php echo URL_BASE; ?>alterar-senha">Alterar senha</a></li>
                        <li><a href="<?php echo URL_BASE; ?>relatorios">Relatório</a></li>
                        <?php endif ?>
                        <li class="divider"></li>
                        <li><a href="<?php echo URL_BASE; ?>sair">Sair</a></li>
                      </ul>
                </li>
                <li>
                    <a href="<?php echo URL_BASE; ?>sair">
                        Sair
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>