<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-user">
                <div class="content">
                    <h3>Dados do Fornecedor</h3>
                    <?php foreach ($fornecedores as $key => $value): ?>
                    <div class="row">
                        <div class="col-md-12">
                            <p><b>#ID</b> <?php echo $value->id; ?></p>
                            <p><b>Nome</b> <?php echo $value->nome; ?></p>
                            <p><b>Capital Social</b> <?php echo $value->capital_social; ?></p>
                            <p><b>Tipo de Empresa</b> <?php echo $value->tipoempresas->nome; ?></p>
                            <p><b>Ramo de Negócios</b> <?php echo $value->ramodenegocios->nome; ?></p>
                            <p><b>Natureza Jurídica</b> <?php echo $value->naturezajuridica->nome; ?></p>
                            <p><b>Inscrição Estadual</b> <?php echo $value->inscricao_estadual; ?></p>
                            <p><b>Linha de Produto</b> <?php echo $value->linha_produto; ?></p>
                            <p><b>Agência</b> <?php echo $value->agencia; ?></p>
                            <p><b>Conta Corrente</b> <?php echo $value->conta_corrente; ?></p>
                            <p><b>Cadastrado em</b> <?php echo date('d/m/Y H:i:s', strtotime($value->created_at)); ?></p>
                        </div>    
                    </div>
                    <?php endforeach ?>
                </div>
                <div class="footer">
                    <a href="<?php echo URL_BASE; ?>fornecedor" class="btn btn-defualt">Tabela Principal</a>
                    <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                    <a href="<?php echo URL_BASE ?>painel/fornecedores/edit/<?php echo $value->id ?>" class="btn btn-defualt">Atualizar</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>