<!--  
	Arquivo gerado pelo Build_Core 
	@author Maickon Rangel - maickon4developers@gmail.com
	Prodigio Framework - 2017
	View: pacientes
-->
<div class="row">
    <div class="col-md-12">
		<h1>Bem vindo <?php echo $_SESSION['nome']; ?></h1>
		<?php if (empty($agendas[0]->id)): ?>
			<p class="alert alert-warning">Você ainda não tem nenhuma consulta marcada.</p>
		<?php else: ?>
			<p>Todas as consultas já cadastradas podem ser visualizadas no relatório abaixo. Por padrão as consultas que ainda estão ativas são exibidas primeiro.</p>
			<div class="col-md-12">
				<div class="content table-responsive table-full-width">
					<table class="table table-striped table-no-bordered table-hover dataTable dtr-inline" id="datatables">
				        <thead>
				            <tr>
				                <th>Status</th>
				                <th>Dentista</th>
				                <th>Paciente</th>
				                <th>Tratamento</th>
				                <th>Data Marcada</th>
				                <th>Observações</th>
				            </tr>
				        </thead>
				        <tbody id="tbody">
				        <?php foreach ($agendas as $key => $value) { ?>
				        	<?php 
				        		if (strtotime(date('Y-m-d H:i:s')) > strtotime($value->data_hora)):
				        			$status = 'Vencido';
				        			$css = 'alert alert-danger';
				        	 	else:
				        			$status = 'Ativo';
				        			$css = 'alert alert-success';
				        	 	endif; 
				        	 ?>
				        	<?php echo "<tr>"; ?>
				        	<?php echo "<td class=\"{$css}\">{$status}</td>"; ?>
				        	<?php echo "<td>{$agenda->retornar_nome($value->id_dentistas)}</td>"; ?>
				        	<?php echo "<td class=\"alert alert-warning\">{$agenda->retornar_nome($value->id_pacientes)}</td>"; ?>
				        	<?php echo "<td>{$value->tratamentos->nome}</td>"; ?>
				        	<?php echo "<td>{$agenda->formatar_data_para_escrita($value->data_hora)}</td>"; ?>
				        	<?php echo "<td>{$value->anotacoes}</td>"; ?>
				        	<?php echo "</tr>"; ?>
				        <?php } ?>
				        </tbody>
				    </table>
				</div>
			</div>
		<?php endif ?>
    </div>
</div>
