<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <?php $this->alert->show($_QUERY); ?>
                    <div class="header">
                        <p class="title">Editar Convênio</p>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>atualizar-convenio" data-toggle="validator">
                            <input type="hidden" name="id" value="<?php echo $convenios[0]->id; ?>">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>CNPJ</label>
                                        <input type="text" autofocus="true" class="form-control" id="cnpj" name="cnpj" placeholder="CNPJ" value="<?php echo $convenios[0]->cnpj; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Razão Social</label>
                                        <input type="text" class="form-control" name="razao_social" placeholder="Razão Social" value="<?php echo $convenios[0]->razao_social; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nome Fantasia</label>
                                        <input type="text" class="form-control" name="nome_fantasia" placeholder="Nome Fantasia" value="<?php echo $convenios[0]->nome_fantasia; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Data de Assinatua</label>
                                        <div class="input-group date datepicker">
                                            <input type='text' class="form-control" name="data_assinatura" placeholder="Data de Assinatura" value="<?php echo date('d/m/Y', strtotime($convenios[0]->data_assinatura)); ?>" required />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Prazo de vigilância</label>
                                        <div class="input-group date datepicker">
                                            <input type="text" class="form-control" name="prazo_vigilancia" placeholder="Prazo de Vigilância" value="<?php echo date('d/m/Y', strtotime($convenios[0]->prazo_vigilancia)); ?>" required />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Tipo</label>
                                        <input type="text" class="form-control" name="tipo" placeholder="Tipo" value="<?php echo $convenios[0]->tipo; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Valor Reembolso</label>
                                        <input type="text" class="form-control" id="valor_reembolso" name="valor_reembolso" placeholder="Valor Reembolso" value="<?php echo $convenios[0]->valor_reembolso; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="text" class="form-control" name="email" placeholder="Email" value="<?php echo $convenios[0]->email; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Site</label>
                                        <input type="text" class="form-control" name="site" placeholder="Site" value="<?php echo $convenios[0]->site; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Telefone</label>
                                        <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Telefone" value="<?php echo $convenios[0]->telefone; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Objetivo</label>
                                        <input type="text" class="form-control" name="objetivo" placeholder="Objetivo" value="<?php echo $convenios[0]->objetivo; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                             
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Rua</label>
                                        <input type="text" class="form-control" name="rua" placeholder="Rua" value="<?php echo $convenios[0]->rua; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Bairro</label>
                                        <input type="text" class="form-control" name="bairro" placeholder="Bairro" value="<?php echo $convenios[0]->bairro; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text" class="form-control" name="numero" placeholder="Número" value="<?php echo $convenios[0]->numero; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Cidade</label>
                                        <input type="text" class="form-control" name="cidade" placeholder="Cidade" value="<?php echo $convenios[0]->cidade; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Cep</label>
                                        <input type="text" class="form-control" name="cep" placeholder="cep" value="<?php echo $convenios[0]->cep; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select autofocus="true" id="fk_estados" name="fk_estados" class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                            <option value="">Selecione</option>
                                            <?php foreach ($estados as $key => $value): ?>
                                            <option <?php echo ($convenios[0]->estados->id == $value->id)?'selected':''; ?> value="<?php echo $value->id; ?>"><?php echo "{$value->nome} ({$value->uf})"; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                        <div class="help-block with-errors" id="horario-erro"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <input type="text" class="form-control" name="status" placeholder="Status" value="<?php echo $convenios[0]->status; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>
                                        <textarea name="descricao" required class="form-control"><?php echo $convenios[0]->descricao; ?></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                            <button type="submit" class="btn btn-default pull-right">Atualizar dados</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>