<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <?php $this->alert->show($_QUERY); ?>
                    <div class="header">
                        <p class="title">Novo Convênio</p>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>criar-convenio" data-toggle="validator">
                           
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>CNPJ</label>
                                        <input type="text" autofocus="true" class="form-control" id="cnpj" name="cnpj" placeholder="CNPJ" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Razão Social</label>
                                        <input type="text" class="form-control" name="razao_social" placeholder="Razão Social" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nome Fantasia</label>
                                        <input type="text" class="form-control" name="nome_fantasia" placeholder="Nome Fantasia" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Data de Assinatua</label>
                                        <div class="input-group date datepicker">
                                            <input type="text" class="form-control" name="data_assinatura" placeholder="Data de Assinatura" value="" required />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Prazo de vigilância</label>
                                        <div class="input-group date datepicker">
                                            <input type="text" class="form-control" name="prazo_vigilancia" placeholder="Prazo de Vigilância" value="" required />
                                            <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                        </div>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Tipo</label>
                                        <input type="text" class="form-control" name="tipo" placeholder="Tipo" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Valor Reembolso</label>
                                        <input type="text" class="form-control" id="valor_reembolso" name="valor_reembolso" placeholder="Valor Reembolso" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="text" class="form-control" name="email" placeholder="Email" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Site</label>
                                        <input type="text" class="form-control" name="site" placeholder="Site" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Telefone</label>
                                        <input type="text" class="form-control" id="telefone" name="telefone" placeholder="Telefone" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Objetivo</label>
                                        <input type="text" class="form-control" name="objetivo" placeholder="Objetivo" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                             
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Rua</label>
                                        <input type="text" class="form-control" name="rua" placeholder="Rua" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Bairro</label>
                                        <input type="text" class="form-control" name="bairro" placeholder="Bairro" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text" class="form-control" name="numero" placeholder="Número" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Cidade</label>
                                        <input type="text" class="form-control" name="cidade" placeholder="Cidade" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Cep</label>
                                        <input type="text" class="form-control" id="cep" name="cep" placeholder="cep" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Estado</label>
                                        <select id="fk_estados" name="fk_estados" class="form-control selectpicker" data-title="Selecione" data-style="btn-default btn-block" data-menu-style="dropdown-blue" required>
                                            <option value="">Selecione</option>
                                            <?php foreach ($estados as $key => $value): ?>
                                            <option value="<?php echo $value->id; ?>"><?php echo "{$value->nome} ({$value->uf})"; ?></option>
                                            <?php endforeach ?>
                                        </select>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <input type="text" class="form-control" name="status" placeholder="Status" value="" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>
                                        <textarea name="descricao" required class="form-control"></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                            <button type="submit" class="btn btn-default pull-right">Salvar dados</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>