<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <?php $this->alert->show($_QUERY); ?>
                    <div class="header">
                        <p class="title">Atualizar Tratamento</p>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>atualizar-tratamento" data-toggle="validator">
                            <input type="hidden" name="id" value="<?php echo $tratamentos[0]->id; ?>">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text" autofocus="true" class="form-control" id="nome" name="nome" placeholder="Nome" value="<?php echo $tratamentos[0]->nome; ?>" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Preço</label>
                                        <input type="text" class="form-control" id="preco" name="preco" placeholder="Preço" value="<?php echo $tratamentos[0]->preco; ?>" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Descrição</label>
                                        <textarea class="form-control" id="descricao" name="descricao" placeholder="Descrição" required=""><?php echo $tratamentos[0]->descricao; ?></textarea>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>
                            <a href="javascript:window.history.go(-1)" class="btn btn-defualt">Voltar</a>
                            <button type="submit" class="btn btn-default pull-right">Atualizar dados</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>