<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-user">
                <?php $this->alert->show($_QUERY); ?>
                <div class="content">
                    <div class="row">
                        <div class="col-md-6">
                            <p class="title">Dentistas</p>
                        </div>
                        <div class="col-md-6">
                            <p class="text-right">
                                <a href="<?php echo URL_BASE; ?>novo-usuario" class="btn btn-default">Cadastrar novo dentista</a>
                            </p>
                        </div>
                    </div>
                    <div class="content table-responsive table-full-width">
                        <table class="table table-striped table-no-bordered table-hover dataTable dtr-inline" id="datatables">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Tipo</th>
                                    <th>Nome</th>
                                    <th>Telefone</th>
                                    <th>Dias de Trabalho</th>
                                    <th>Horário</th>
                                    <th></th>
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="tbody">
                            <?php foreach ($dentistas as $key => $value): ?>
                            <tr>
                                <td class="icon_table"><?php echo $value->id ?></td>
                                <td><?php echo isset($value->tipos->nome)?$value->tipos->nome:''; ?></td>
                                <td><?php echo $value->nome; ?></td>
                                <td><?php echo $value->telefone; ?></td>
                                <td><?php echo "<small class=\"dias\">{$usuario->formatar_dias($value->fk_dias)}</small>";?></td>
                                <?php $inicio = date('H:i', strtotime($value->horario_atendimento_inicio)); ?>
                                <?php $fim = date('H:i', strtotime($value->horario_atendimento_fim)); ?>
                                <td><?php echo "Das {$inicio}hs às {$fim}hs"; ?></td>
                                <td><a href="<?php echo URL_BASE ?>painel/usuarios/show/<?php echo $value->id ?>"><div class="pe-7s-door-lock icon_table"></div></a></td>
                                <td><a href="<?php echo URL_BASE ?>painel/usuarios/edit/<?php echo $value->id ?>"><div class="pe-7s-pen icon_table"></div></td>
                                <td>
                                    <a href="#"><div class="pe-7s-trash icon-table icon_table" onclick="delete_data(<?php echo $value->id ?>,<?php echo $value->fk_tipos ?>);" data-toggle="modal" data-target="#deleteModal">
                                    </div></a>
                                </td>
                            </tr>
                            <?php endforeach ?>
                            </tbody>
                        </table>
                        
                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <form method="post" action="<?php echo URL_BASE; ?>excluir-usuario">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                                <h4 class="modal-title" id="myModalLabel">Tem certeza que deseja deletar este usuário?</h4>
                                            </div>
                                        <div class="modal-body" id="modal-body-view">
                                            <p>Você está prestes a deletar um usuário.</p>
                                            <input type="hidden" name="id" id="id">
                                        </div>
                                        <div class="modal-footer">
                                            <button type="submit" id="delete_url" class="btn btn-red btn-fill">Sim</button>
                                            <a href="#" class="btn btn-red btn-fill" data-dismiss="modal">Não</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>