<!--  
	Arquivo gerado pelo Build_Core 
	@author Maickon Rangel - maickon4developers@gmail.com
	Prodigio Framework - 2017
	View: usuarios
-->
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Nova conta</h4>
                    </div>
                    <div class="content">
                        <form method="post" action="<?php echo URL_BASE; ?>cadastrar" data-toggle="validator">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Nome</label>
                                        <input type="text" autofocus="true" class="form-control" name="nome" placeholder="Nome" value="" required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control" name="email" placeholder="Email" value="" data-error="Por favor, informe um e-mail correto." required>
                                        <div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Telefone</label>
                                        <input type="text" class="form-control" name="telefone" placeholder="Telefone" value="" data-mask="(00)00000-0000" maxlength="12" type="telephone" required>
                                        <span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Senha</label>
                                        <input type="password" class="form-control" name="senha" placeholder="Senha" id="senha" value="" data-minlength="6" data-error="Mínimo de seis (6) digitos" required>
										<span class="help-block with-errors"></span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Confirmar Senha</label>
                                        <input type="password" class="form-control" placeholder="Confirmar senha" value="" data-match="#senha" data-match-error="Atenção! As senhas não estão iguais." required>
										<div class="help-block with-errors"></div>
                                    </div>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-default pull-right">Criar conta</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>