<h2 align="center">AGENDA</h2>

<h2>Reserve o seu horário</h2>

<p>Para uma melhor comodidade dos nossos cliente, realizamos nossas consultas e tratamentos com horário reservado, para uma melhor safisfação de nossos clientes.

<br>

<b>Central de Atendimento</b>

<br>

(22) 3052-8975.

Nossos atendentes estão aguardando a sua ligação. Ligue e faça a reserva do seu horário.
Cumprimos o horário agendado. Sempre visando a excelência de nossos serviços. 
</p>

<h2>Qualidade</h2>

<p>Para realizarmos os nossos trabalhos da melhor forma possível e que os nossos cliente fiquem satisfeitos, sempre buscamos trabalhar com produtos de melhor qualidade, afinal de contas essa é a nossa Missão, oferecer tratamento odontológico de qualidade e acessível a todos, buscando sempre a satisfação de nossos clientes.</p>

<h2>Inovações</h2>

<p>Um dos nossos diferenciais são as inovações que trazemos a cada dia para os nossos clientes, tanto na área de tratamento, quanto na área de produtos, atendimento, etc... Para ser manter vivo em um mercado competitivo, precisa-se acompanhar a evolução.</p>
