<h2 align="center">CONVÊNIOS</h2>

<h2>Planos</h2>

<p>Leve todo o nosso tratamento odontológico para você e sua família, temos um plano exclusivo familiar, ofecerecemos um plano que vai caber no seu orçamento, venho conhecê-lo.</p>
<p>Você empresário não perca tempo, venha conhecer o plano odontológico empresarial que temos exclusivo para você, para atender todas as suas necessidades, para que você sempre veja os seus colaboradores com um sorriso perfeito. </p>

<p>Atendemos também diversos convênios, para sempre pode atender você que é nosso cliente.</p>

<h2>Credenciados</h2>

<p>Para você que já é credenciado a algum plano de saúde, não parca tempo e venha cuida da sua saúde bucal conosco, onde temos todo o diferencial em tratamento odontológico, para você, para sua família e para a sua empresa.</p>

<h2>Parceiros</h2>

<p>Temos passado a cada dia, mais confiança para os nossos parceiros, e com isso temos conseguido obter novos parceiros, onde você possa vê em nossa empresa a seriedade dos nossos serviços, juntamente com a qualidade e a execução de forma a garantir em primeiro lugar a sua satisfação e além disso sempre seguindo os padrões odontológicos.</p>