<html>
<head>
	<title><?php echo $this->meta_title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="description" content="<?php echo $this->meta_description; ?>" />
	<meta name="keywords" content="<?php echo $this->meta_keywords; ?>" />
    <link rel="shortcut icon" href="<?php URL_BASE; ?>app/assets/img/favicon144x144.png">
	<?php //echo $this->css_files; ?>
	<link href="<?php echo URL_BASE; ?>app/assets/css/bootstrap.min.css" rel="stylesheet"/>
	<link href="<?php echo URL_BASE; ?>app/assets/css/animate.min.css" rel="stylesheet"/>
	<link href="<?php echo URL_BASE; ?>app/assets/css/light-bootstrap-dashboard.css" rel="stylesheet"/>
    <link href="<?php echo URL_BASE; ?>app/assets/css/pe-icon-7-stroke.css" rel="stylesheet"/>
	<link href="<?php echo URL_BASE; ?>app/assets/css/index.css" rel="stylesheet"/>
</head>
<body> 
    <nav class="navbar navbar-default  menu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo URL_BASE; ?>">Sis Odonto</a>
            </div>
            <div class="collapse navbar-collapse">               
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href="<?php echo URL_BASE; ?>">
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>tratamentos">
                            Tratamentos
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>agendas">
                            Agenda
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>produtos">
                           Produtos
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>convenios">
                           Convênios
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>fornecedores">
                           Fornecedores
                        </a>
                    </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    <?php if (isset($_SESSION['id'])): ?>
                    <li>
                        <a href="<?php echo URL_BASE; ?>painel">
                            Painel Administrativo
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE; ?>sair">
                            Sair
                        </a>
                    </li>                        
                    <?php else: ?>
                    <!-- <li>
                        <a href="<?php //echo URL_BASE; ?>nova-conta">
                            Criar uma conta
                        </a>
                    </li> -->
                    <li>
                        <a href="<?php echo URL_BASE; ?>login">
                            Entrar
                        </a>
                    </li>
                    <?php endif ?>
                </ul>
            </div>
        </div>
    </nav>
    <div id="logo-bar"><img id="logo" src="<?php echo URL_BASE; ?>app/assets/img/logo.png"></div>
    <section class="body">
        <div class="container">
            <?php require_once $this->content(); ?>
        </div>
    </section>
    <footer class="footer">
        <div class="container">
            <nav class="pull-left">
                <ul>
                    <li>
                        <a href="<?php echo URL_BASE; ?>">
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>tratamentos">
                            Tratamentos
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>agendas">
                            Agenda
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>produtos">
                           Produtos
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>convenios">
                           Convênios
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo URL_BASE ?>fornecedores">
                           Fornecedores
                        </a>
                    </li>
                </ul>
            </nav>
            <p class="copyright pull-right">
            	Equipe Sis Odonto Desenvolvimento - &copy <?php echo date("Y"); ?>
            </p>
        </div>
    </footer>

	<?php //echo $this->js_files; ?>
	<script src="<?php echo URL_BASE; ?>app/assets/js/jquery-1.10.2.js" type="text/javascript"></script>
	<script src="<?php echo URL_BASE; ?>app/assets/js/bootstrap.min.js" type="text/javascript"></script>
	<script src="<?php echo URL_BASE; ?>app/assets/js/bootstrap-notify.js" type="text/javascript"></script>
    <script src="<?php echo URL_BASE; ?>app/assets/js/light-bootstrap-dashboard.js" type="text/javascript"></script>
    <script src="<?php echo URL_BASE; ?>app/assets/js/validator.js" type="text/javascript"></script>
	<script src="<?php echo URL_BASE; ?>app/assets/js/jquery.mask.js" type="text/javascript"></script>
</body>
</html>